server:
  port: 8001    #服务端口

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.founderbn.springcloud.entities   #实体类包名
  mapper-locations: classpath:mybatis/mapper/**/*.xml        #mapper映射文件


spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
      test-while-idle: false
      validation-query: SELECT 1
logging:
  level:
    com.founderbn.springcloud.dao: debug







